// export const GET_VALUE = 'GET_VALUE'
// export const GET_ETXTAREA = 'GET_ETXTAREA'
// export const GET_CLASSIFY = 'GET_CLASSIFY'
// export const SUBMIT = 'SUBMIT'
// export const GET_SERVER_CLASSIFY= 'GET_SERVER_CLASSIFY'
